### PR TITLE
Plugin #install and #remove

### PR DESCRIPTION
**Pull request by endorama**
Add 2 new methods ( install and remove ) to install and remove wordpress plugins. Added tests.

I need to add php-serialize gem because wordpress plugin api return php serialized object, instead of json or similar type of data.

### CODE REVIEW

**Comment by etienne** [comment]
Thanks a lot! It all looks great. I'm wondering though whether "install" and "remove" are the best method names. My first instinct was to rename "remove" to "uninstall", as that seems more consistent. Now that I've given it some more thought though, I'm wondering if "install" is misleading in the context of a WordPress installation. It could refer to the installation of WordPress itself, or to a plugin, or to a theme. What do you think?

How about `wordpress plugin install <pluginname>` and `wordpress plugin uninstall <pluginname>`? Too verbose?

**Comment by endorama** [comment]
I think that would be a great solution, but actually I don't know how to do it... Can you implement this yourself?

We could also add `wordpress themes install/uninstall <themename>`!

**Comment by etienne** [comment]
I'll look into it. Maybe it'll have to be plugin:install and plugin:uninstall, I don't remember what's easiest with Thor.

One thing I've been wondering also is whether I should deprecate this tool and move to [wp-cli](https://github.com/wp-cli/wp-cli), which is much more full-featured... have you ever used it? I don't want to rush the move, but looking at the functionalities it has, I'm wondering if it's worth the effort duplicating it as a Ruby gem. What do you think?

**Comment by endorama** [comment]
Looking at the code seems great... it uses the wordpress functions to
interact with the wordpress installation, is written in php ( which I think
is best for interaction with a php CMS ) and has lots of features already
presents...

There's only one thing which seems to me a little bad: how can you make the
installation of wp-cli transparent for the end-user?

**Comment by etienne** [comment]
That's the part I need to figure out. I would probably include wp-cli as a git submodule in the wordless_gem project, and maybe automate installation as part of the gem installation process... not too sure.

Did you intend to use this gem (wordpress_tools) independently of the Wordless gem?

**Comment by endorama** [comment]
> Did you intend to use this gem (wordpress_tools) independently of the
> Wordless gem?

Yes... I was trying to  find a method to automatize plugin installation...

**Comment by endorama** [comment]
Also, as stated in this Wp-Cli presentation, wp-cli can be [extended by plugins](http://scribu.net/wordpress/a-command-line-interface-for-wordpress.html)

Maybe could be a good idea to integrate the whole wordless gem into it?

**Pull request closed without merging**
